création du squelette de jeu et des méthodes
projet-gl2/Hashimiste pull request #1
Opened 2024-01-29 11:11 UTC by ilyaizu

2024-01-30 08:35 UTC, enimaloc requested changes

2024-01-30 08:35 UTC, enimaloc commented on src/main/java/Jeu.java
> +    ArrayList<Boutons> listeBoutons = new ArrayList<Boutons>();
manque un modificateur de portée

2024-01-30 08:35 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public Jeu(/*la grille de jeu*/, /* la grile solution*/){
manque la javadoc

2024-01-30 08:35 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void retourArriere(){
manque la javadoc

2024-01-30 08:35 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void poserCheckpoint(){
manque la javadoc

2024-01-30 08:35 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void chargerCheckpoint(){
manque la javadoc

2024-01-30 08:35 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void verifierGrille(){
manque la javadoc
`/* Méthode qui vérifie île par île si la grille est bonne*/` n'est pas considérer comme de la javadoc
La javadoc est sous cette forme
```java
/**
  * Doc
  **/
```

2024-01-30 13:21 UTC, enimaloc requested changes

2024-01-30 13:21 UTC, enimaloc commented on src/main/java/Aventure.java
> +    public Aventure(int nbBouton, int largeurBouton, int hauteurBouton) {
manque la javadoc  
`/* Méthode qui vérifie île par île si la grille est bonne*/` n'est pas considérer comme de la javadoc  
La javadoc est sous cette forme

```java
/**
  * Doc
  **/
```

2024-01-30 13:21 UTC, enimaloc commented on src/main/java/Aventure.java
> +public class Aventure {
manque la javadoc  
`/* Méthode qui vérifie île par île si la grille est bonne*/` n'est pas considérer comme de la javadoc  
La javadoc est sous cette forme

```java
/**
  * Doc
  **/
```

2024-01-30 13:21 UTC, enimaloc commented on src/main/java/Aventure.java
> +    public static void main(String[] args) {
manque la javadoc  
`/* Méthode qui vérifie île par île si la grille est bonne*/` n'est pas considérer comme de la javadoc  
La javadoc est sous cette forme

```java
/**
  * Doc
  **/
```

2024-02-05 09:47 UTC, enimaloc requested changes

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +    public Aventure(int nbBouton, int largeurBouton, int hauteurBouton) {
Si tu peut ajouter plus de précision avec les `@param` et `@return`

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +             **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +         * */
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Aventure.java
> +    public static void main(String[] args) {
Si tu peut ajouter plus de précision avec les `@param`

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public Jeu(/*la grille de jeu*/, /* la grile solution*/){
Pas de javadoc ici

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void retourArriere(){
Pas de javadoc ici

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void poserCheckpoint(){
Pas de javadoc ici

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +    public void chargerCheckpoint(){
Pas de javadoc ici

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 09:47 UTC, enimaloc commented on src/main/java/Jeu.java
> +         **/
Pas besoin de les mettre comme cela dans les méthodes un simple `//` suffit

2024-02-05 10:11 UTC, DamiBoul approved these changes

2024-02-05 10:20 UTC, enimaloc approved these changes

2024-02-05 10:25 UTC, merged