ajout corps méthode aide + import Technique + ajout méthode isComplet…
projet-gl2/Hashimiste pull request #18
Opened 2024-03-13 10:45 UTC by DamiBoul

…e dans Ile

2024-03-13 14:04 UTC, enimaloc requested changes

2024-03-13 14:04 UTC, enimaloc commented on src/main/java/fr/hashimiste/core/jeu/Ile.java
> +    public boolean isComplete();
Le `public` n'est pas nécessaire ici

2024-03-26 08:31 UTC, tetelie approved these changes

2024-04-02 09:53 UTC, enimaloc approved these changes

2024-04-02 09:54 UTC, merged