Interface pull request, test unitaire et fin de l'interface des menus
projet-gl2/Hashimiste pull request #20
Opened 2024-03-26 09:29 UTC by MasterPNJ

Tout les teste unitaires sur les menus ont été effectués et l'interface des menus sont fini.

2024-03-26 09:40 UTC, DamiBoul approved these changes

2024-04-01 18:40 UTC, enimaloc requested changes

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/AventureTest.java
> +class AventureTest extends fr.hashimiste.impl.gui.menu.Test{
utiliser la directive `import`

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/AventureTest.java
> +    void TestMenuParametre(){
par convention les méthodes commence par une minuscule

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/MenuTest.java
> +class MenuTest extends fr.hashimiste.impl.gui.menu.Test {
utiliser la directive `import`

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/ModeLibreTest.java
> +class ModeLibreTest extends fr.hashimiste.impl.gui.menu.Test{
utiliser la directive `import`

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/ParametreTest.java
> +class ParametreTest extends fr.hashimiste.impl.gui.menu.Test{
utiliser la directive `import`

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/ProfilSelectionTest.java
> +class ProfilSelectionTest extends fr.hashimiste.impl.gui.menu.Test{
utiliser la directive `import`

2024-04-01 18:40 UTC, enimaloc commented on src/test/java/fr/hashimiste/impl/gui/menu/TechniqueTest.java
> +class TechniqueTest extends fr.hashimiste.impl.gui.menu.Test{
utiliser la directive `import`

2024-04-02 07:08 UTC, enimaloc approved these changes

2024-04-02 07:08 UTC, merged