Interfaces pour les différentes pages
projet-gl2/Hashimiste pull request #7
Opened 2024-02-06 11:06 UTC by HiraAkshayy

2024-02-08 10:17 UTC, enimaloc requested changes

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Couleur.java
> +    public final static java.awt.Color couleurTransparent=new java.awt.Color(0x00000000, true);
Import ces classes directement dans le headers du fichier

```java
import java.awt.Color;
```

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Couleur.java
> +    }
Ici, cette classe représente une classe de constante je ferais donc plus

```suggestion
    public final static Color COULEUR_BOUTON = new Color(160, 158, 188);
    public final static Color COULEUR_TEXTE_BOUTON = new Color(251, 250, 242);
    public final static Color COULEUR_BOUTON_DESACTIVE = new Color(197, 179, 179);
    public final static Color COULEUR_FOND = new Color(251,250,242);
    public final static Color COULEUR_TRANSPARENT = new Color(0x00000000, true);
    
    /**
      * Constructeur privée pour éviter l'instanciation
     **/
    private Couleur() {}
```

Sans oublié la documentation

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Image.java
> +    private final static String logoTitreTransparent = "src/main/resources/images/logoTitreTransparent.png";
La convention pour les constantes est `UPPER_SNAKE_CASE` est non en `camelCase`

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Menu.java
> +    private final int tailleButX = 50;
Les constantes sont en `UPPER_SNAKE_CASE` et non en `camelCase`

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Menu.java
> +    private final int tailleButX = 50;
Maybe mettre en `static` cela ne sert à rien de recréer une variable pour ces constante primitive

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Menu.java
> +    }
Réduire cette méthode d'URGENCE, 350 lignes ce n'est pas possible !

> Ce point est un veto pour l'approbation de la PR

Utilise l'import de classe tel que

```java
import java.awt.Dimension;
import java.awt.Color;
import java.awt.event.MouseListener;
import java.awt.event.MouseEvent;
```

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/MenuParametres.java
> +    private Color couleurTextBouton = new java.awt.Color(251, 250, 242);
On peut enlever `java.awt.` car la classe est déjà importé par `import java.awt.*;`

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/MenuParametres.java
> +    private int tailleMaxY = 1080;
Peut être des constantes

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/Image.java
> +}
Cette classe est une classe constante on peut la remplacer par:

```suggestion
public class Image {
    public final static String cheminIcone = "src/main/resources/images/icon.png";
    public final static String cheminIconeTransparent = "src/main/resources/images/iconTransparent.png";
    public final static String logo = "src/main/resources/images/logo.png";
    public final static String logoOriginal = "src/main/resources/images/logoOriginal.png";
    public final static String logoTitre = "src/main/resources/images/logoTitre.png";
    public final static String logoTitreTransparent = "src/main/resources/images/logoTitreTransparent.png";
    
    /**
      * Constructeur privée pour éviter l'instanciation
     **/
    private Image() {}
}
```

Sans oublier la documentation

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/MenuProfilCreation.java
> +    */
La javadoc ne correspond pas a ce qu'elle cible

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/MenuProfilCreation.java
> +        this.setMinimumSize(new java.awt.Dimension(1000, 720));
Import ces classes directement dans le headers du fichier

```java
import java.awt.Dimension;
```

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/MenuProfilCreation.java
> +   public static void main(String[] args){
Manque de la javadoc ici

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/MenuTechnique.java
> +    private int tailleMaxY = 1080;
Peut être déclarer en tant que constantes

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/ModeLibre.java
> +    private final int tailleMaxY = 1080;
Peut être mis en `static`

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/ModeLibre.java
> +                System.out.println(c.getClass());
Ne pas oublier de retirer les variable de débug

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/PreviewComponent.java
> +                g.setFont(new Font("Andale Mono", Font.BOLD, t));
Déclarer l'instance en tant que constante sera bénéfique

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/PreviewComponent.java
> +        this.setMinimumSize(new Dimension(50,50));
Déclarer les Magic Value en tant que constante sera bénéfique

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/PreviewComponent.java
> +public class PreviewComponent extends JComponent {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/PreviewComponent.java
> +    public void setColor(Color color) {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/gui/modelibre/PreviewComponent.java
> +    public Color getColor() {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/techniques/Ile.java
> +    public int getN() {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/techniques/Ile.java
> +    public int getX() {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/techniques/Ile.java
> +    public int getY() {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/techniques/Ile.java
> +    public Grille getGrille() {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/main/java/fr/hashimiste/techniques/Ile.java
Il faudrais récupérer l'état actuelle de la branche pour pouvoir remplacer cette classe par `fr.hashimiste.maps.Ile`

2024-02-08 10:17 UTC, enimaloc commented on src/test/java/fr/hashimiste/gui/ModeLibreGui.java
> +    public static void main(String[] args) {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/test/java/fr/hashimiste/gui/ModeLibreGui.java
> +public class ModeLibreGui {
Manque de la javadoc

2024-02-08 10:17 UTC, enimaloc commented on src/test/java/fr/hashimiste/gui/ModeLibreGui.java
Je suppose que cette classe est toujours en cours de construction, indiquer là avec `#TODO: A implémenter`

2024-02-08 10:17 UTC, enimaloc commented on src/main/resources/images/iconTransparent.png
Au lieu de mettre plusieurs image, peut-être modifier une image originale en plusieurs variantes ?

2024-02-08 10:17 UTC, enimaloc commented on src/main/resources/images/icon.png
Au lieu de mettre plusieurs image, peut-être modifier une image originale en plusieurs variantes ?

2024-02-08 10:17 UTC, enimaloc commented on src/main/resources/images/logo.png
Au lieu de mettre plusieurs image, peut-être modifier une image originale en plusieurs variantes ?

2024-02-08 10:17 UTC, enimaloc commented on src/main/resources/images/logoTitre.png
Au lieu de mettre plusieurs image, peut-être modifier une image originale en plusieurs variantes ?

2024-02-08 10:17 UTC, enimaloc commented on src/main/resources/images/logoTitreTransparent.png
Au lieu de mettre plusieurs image, peut-être modifier une image originale en plusieurs variantes ?

2024-02-08 16:48 UTC, DamiBoul requested changes

2024-02-08 16:48 UTC, DamiBoul commented on src/main/java/fr/hashimiste/gui/Menu.java
> +    private final int tailleButX = 50;
je veux pas être rabat joie mais il me semble qu'il faut aussi mettre de la documentation sur les constantes ?

2024-02-09 10:48 UTC, tetelie commented on src/test/java/fr/hashimiste/gui/ModeLibreGui.java
c'est une classe de test

2024-02-09 15:58 UTC, DamiBoul approved these changes

2024-02-14 12:33 UTC, enimaloc approved these changes

2024-02-14 12:33 UTC, merged