Feat/db
projet-gl2/Hashimiste pull request #8
Opened 2024-02-10 15:12 UTC by KylianPatault

On avait fait ça avec Lucas, tous les fichiers sont commentés

2024-02-15 12:40 UTC, DamiBoul approved these changes

2024-02-15 15:19 UTC, DamiBoul approved these changes

2024-02-21 14:28 UTC, DamiBoul requested changes

2024-02-21 14:28 UTC, DamiBoul commented on src/main/java/fr/hashimiste/Ile.java
> +    public int x, y, n;
est-ce qu'on est bien sûr de vouloir mettre en public plutôt que de faire des getters ?

2024-02-21 14:28 UTC, DamiBoul commented on src/main/java/fr/hashimiste/Pont.java
> +    public int n;
est-ce qu'on est bien sûr de vouloir mettre en public plutôt que de faire des getters ?

2024-02-21 14:28 UTC, DamiBoul commented on src/main/java/fr/hashimiste/maps/Ile.java
> +
il manque trois méthodes ici que j'avais ajouté, getNbVoisin, getNbVoisinAvec1  et nbPontsDirection

2024-02-21 14:43 UTC, enimaloc commented
Je vais refaire bien au propre, je merge, et je vais faire cela sur fix/common

2024-02-21 14:45 UTC, merged